site_name: Polygon ID Documentation tutorials

site_url: https://polygon.technology/polygon-id/
theme:
  name: material
  palette:
    primary: deep purple
  logo: logo-white.svg
  favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - content.tabs.link
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - mkdocs_graphviz
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 


nav:
  - Introduction:
    - What is Polygon ID: "intro/what-is-PID.md"
    - Key concepts: 
      - Decentralized Identifier (DID): "intro/key-concepts/did.md"
      - Verifiable Credentials (VCs) : "intro/key-concepts/vc.md"
      - Query Language: "intro/key-concepts/query-language.md"
      - JWZ: "intro/key-concepts/jwz.md" 
    - Solution Architectures: "intro/architectures.md" 
    - Getting Started: "intro/getting-started.md"
  - PID Services: 
    - Introduction: "PID-services/services-intro.md"
  - Identity SDK: 
    - Issuer SDK: "PID-identity-sdk/issuer-sdk/issuer-sdk-intro.md"
    - Verifier SDK: "PID-identity-sdk/verifier-sdk/verifier-sdk-intro.md"
    - Tutorial: "PID-identity-sdk/tutorial/dao-proof-of-personhood.md"
  - Wallet SDK: 
    - Introduction: "PID-wallet-sdk/wallet-sdk-intro.md"



# If you declare plugins, you need to declare all of them, 
# including search (which would otherwise have been installed by default.)
plugins:
  - search
  - mermaid2
