site_name: Polygon ID Documentation tutorials

site_url: https://polygon.technology/polygon-id/
theme:
  name: material
  palette:
    primary: deep purple
  logo: logo-white.svg
  favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - content.tabs.link
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - mkdocs_graphviz
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 


nav:
  - Introduction:
    - What is Polygon ID: "intro/what-is-PID.md"
    - Key concepts: 
      - Issuer: "intro/key-concepts/issuer.md"
      - Verifier : "intro/key-concepts/verifier.md"
      - Wallet: "intro/key-concepts/wallet.md"
    - Solution Architectures: "intro/architectures.md" 
    - Use cases: "intro/use-cases.md"
  - Issuer: 
    - Issuer SDK: "issuer/issuer-sdk/issuer-sdk-intro.md"
  - Verifier:
    - Verifer SDK:
      - Intro: "verifier/verifier-sdk/verifier-sdk-intro.md"
      - Zk Login Workflow: "verifier/verifier-sdk/zk-login-workflow.md"
      - Zk Login Integration: "verifier/verifier-sdk/zk-login-integration.md"
      - Demo: "verifier/verifier-sdk/demo.md"
  - Wallet:
    - Wallet SDK: "wallet/wallet-sdk/wallet-sdk-intro.md"
  - Glossary: "glossary/glossary.md"



# If you declare plugins, you need to declare all of them, 
# including search (which would otherwise have been installed by default.)
plugins:
  - search
  - mermaid2
